{% set name = "slurm-pipeline" %}
{% set version = "4.1.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/slurm-pipeline-{{ version }}.tar.gz
  sha256: 8534162b9494dcf02c8a113704fbbba880949eebfeb03c0c0fc11865879f62a3

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - pandas
    - pip
    - plotly
    - pytest >=6.2.2
    - python >={{ python_min }}
    - toml

test:
  imports:
    - slurm_pipeline
  source_files:
    - test
  commands:
    - pip check
    - pytest test
  requires:
    - pandas
    - pip
    - plotly
    - pytest
    - toml
    - python {{ python_min }}

about:
  home: https://github.com/acorg/slurm-pipeline
  summary: A Python class and utility script for scheduling SLURM jobs
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - terrycojones
